### ISSUE TITLE
Propriedades de Notifiable<T> como 'virtual'

### ISSUE THREAD

**Issue by brailowsky** [andrebaltieri/flunt#111]
Ao serializar (System.Text.Json) objetos implementando Notifiable<T>, eu recebo também as propriedades IsValid e Notifications. Em alguns casos o destino do Json não pode implementar Flunt/Notification, ou seja esses dados extras não serão utlizados - além do maior payload.

Sugestao: Marcar ambas as propriedades como virtual: nao ira afetar implementacoes existentes, a classes que implementem Notifiable<T> poderão, como no meu caso, realizar um override e decorar as propriedades com [JsonIgnore].

**Comment by saldorflorin** [comment]
Olá, gostaria de saber se essa ação já foi implementada? Pois tem um retorno de uma payload muito feia com os values objects retornando em cada um um metodo "Notifications:[]"

**Comment by andrebaltieri** [comment]
Bom dia, pessoal, as propriedades do Flunt não podem ser afetadas por comportamentos individuais, ou seja, se eu colocar o `Ignore` no IsValid eu vou mudar este comportamento para todos que usam o Flunt...

Além disso, o JsonIgnore veio junto com .NET 6+, precisando aumentar a versão da lib e diminuindo a quantidade.
Podemos discutir isto para as próximas versões com Breaking Changes!
