### ISSUE TITLE
Add validation for max quantity of characters (IsMaxLength).

### ISSUE THREAD

**Issue by MarcosCostaDev** [andrebaltieri/flunt#114]
Please, add validation for the max quantity of characters in a string.

```csharp
        var contract = new Contract<Notification>();
        contract.IsMaxLength("My text here", 10, nameof(MyText), "Error on max quantity of characters");
```

**Comment by andrebaltieri** [comment]
Hi @MarcosCostaDev, how are you?

Does `IsGreaterThan` or `IsGreaterOrEqualsThan` works for this scenario?

**Comment by MarcosCostaDev** [comment]
Yes, I am using that. Just a suggestion to be more streightforword.

**Comment by andrebaltieri** [comment]
Great, thanks... will consider this on next version!
