### ISSUE TITLE
Como usar contract com tipo long?

### ISSUE THREAD

**Issue by diegopinguim** [andrebaltieri/flunt#17]
Bom dia! 

Estou tentando aplicar o Flunt em meus projetos, porém eu tenho vários dados com tipo long, como usar o flunt com long?

**Comment by betorolim1** [comment]
Foi criado um pull request com o tipo de validação "long", mas enquanto essa feature não é aprovada, você pode converter seu dado para double e utilizar a validação que já existe deste tipo. 
Exemplo: 
`double doubleValue = Convert.ToDouble(longValue);
 Contract contract = new Contract()
                .Requires()
                .IsBetween(doubleValue, fromVariable, toVariable, "propriedade_utilizada", "mensagem_de_validação")`

**Comment by andrebaltieri** [comment]
This issue was fixed on our new version!

**Comment by stonestecnologia** [comment]
> This issue was fixed on our new version!

Não encontrei, poderia me enviar o link ?

**Comment by betorolim1** [comment]
> > This issue was fixed on our new version!
> 
> Não encontrei, poderia me enviar o link ?

https://github.com/andrebaltieri/flunt/commit/6355dfa0d7538da82a8d81f0fd0b1d4d76954327 link do commit
