### ISSUE TITLE
BoolValidationContract

### ISSUE THREAD

**Issue by Hakkd** [andrebaltieri/flunt#28]
Shoudn't be the crontrary?

On BoolValidationContract IsFalse adds notification if it is true and IsTrue adds notification if is false. Isn't supposed to be the contrary?

**Comment by andrebaltieri** [comment]
A contract requires that some value is true. If it is false, then a validation message will be added to the entity!

**Comment by andrebaltieri** [comment]
Also you can check the testes for more information!
