### ISSUE TITLE
Command's com Validação

### ISSUE THREAD

**Issue by stonestecnologia** [andrebaltieri/flunt#34]
https://github.com/andrebaltieri/flunt/wiki/05.-Fail-Fast-Validations
Boa noite, 
Vc usou desta forma somente pra exemplificar correto ?
Seu command faz as validacoes ...
Nos cursos usamos no Dominio/Entidade...
Correto ?

**Comment by andrebaltieri** [comment]
Por favor, quando for dúvidas não abra issue!
No exemplo eu valido os Commands, podemos validar eles ou as entidades. 
No caso com Fail Fast Validations o ideal é validar os comandos já.
