### ISSUE TITLE
String validation

### ISSUE THREAD

**Issue by alannsiqueira** [andrebaltieri/flunt#36]
String validation not being performed as it should, negations are reversed

https://github.com/andrebaltieri/flunt/blob/72ff8dceec2a5989e98327f53c153ed14a4dbfd6/Flunt/Validations/StringValidationContract.cs#L11

https://github.com/andrebaltieri/flunt/blob/72ff8dceec2a5989e98327f53c153ed14a4dbfd6/Flunt/Validations/StringValidationContract.cs#L19

https://github.com/andrebaltieri/flunt/blob/72ff8dceec2a5989e98327f53c153ed14a4dbfd6/Flunt/Validations/StringValidationContract.cs#L28

**Comment by andrebaltieri** [comment]
Hi Alan,
These methods were implemented since V1, and the testes are passaing:

Test Run Successful.
Total tests: 57
     Passed: 57

They seem fine!
