### ISSUE TITLE
Why Notification class is sealed?

### ISSUE THREAD

**Issue by douglasangeli** [andrebaltieri/flunt#41]
Is there a reasonable design requirement for the [Notification.cs](https://github.com/andrebaltieri/flunt/blob/master/Flunt/Notifications/Notification.cs) class to be `sealed`?

I ask this because I am using Flunt in a project that I need to have my own implementation.

Is there a problem with that?

**Comment by andrebaltieri** [comment]
Great question! When I designed it, I wanted to standardize the way notification outputs were shown, but there`s a downside on it, which is that you can`t extend Notification class.

On version 2 I`ll remove sealed modifier from Notification class.
