### ISSUE TITLE
Notification Types

### ISSUE THREAD

**Issue by diegosanfelix** [andrebaltieri/flunt#45]
Balta,

Very usefull class. 

Wouldn't be nice to have 3 types of notifications (Success, Alert, Error) so we could use the list of notifications to alert to end-users?

- Notification Type could be Optional.
- By default, ERROR type is set if not provided.
- Review Invalid() Method to filter Error Type olny.

**Comment by andrebaltieri** [comment]
Great question! Today Notification class is sealed preventing you to extend it! On version 2, I`ll remove sealed modifier and you`ll be able to create your own notifications, for example:

```csharp
public class Warning : Notification
```

As Warning is child of notification you can upcast it!
