### ISSUE TITLE
Validar CNPJ e CPF

### ISSUE THREAD

**Issue by brunotdantas** [andrebaltieri/flunt#49]
Notei que é usado métodos como IsEmail ou IsURL, acham válido aplicar a validação do IsCpF ou IsCNPJ ?

**Comment by manacespereira** [comment]
opa, bruno, beleza? acho que nesse caso, vc pode usar a lib para o brasil (pois cpf e cnpj são documentos válidos somente aqui)

https://github.com/lira92/flunt.br

**Comment by brunotdantas** [comment]
Legal @manacespereira  não conhecia. Obrigado!
