### ISSUE TITLE
Add default messages to common contract rules

### ISSUE THREAD

**Issue by thiagolunardi** [andrebaltieri/Flunt#5]
WHEN
`
Contract
.Required()
.HasMinLen(x => x.Name, 3)
`
AND
`x.Name = "A";`
THEN
`// output: "Name must have at least 3 characters" ... or so.`

**Comment by andrebaltieri** [comment]
Moved to version 2.0! Check milestones!

**Comment by andrebaltieri** [comment]
Version 2.0.0 released, thanks!
