### ISSUE TITLE
Change property names

### ISSUE THREAD

**Issue by andrebaltieri** [andrebaltieri/Flunt#60]
Some names on `Notifiable.cs` are no intuitive, we`re gonna change to:

```csharp
// From
bool Invalid 
bool Valid
```

```csharp
// To
bool IsNotValid 
bool IsValid
```

**Comment by natancmacedo** [comment]
I totally agree
As you are broking some contract (since some projects use Valid or Invalid) you will create a major version?

**Comment by LucasWBritz** [comment]
> I totally agree
> As you are breaking some contract (since some projects use Valid or Invalid) you will create a major version?

Another option is to keep both and add an [Obsolete]  attribute on the properties. Then he can delete them in a future version. So it won't break anything and will raise some alerts pointing out to use the new properties.

**Comment by andrebaltieri** [comment]
@natancmacedo yeah, will be a major release!!! 
@LucasWBritz great, but as we`ll have a major release, I think it`s not necessary!

**Comment by andrebaltieri** [comment]
Base Notification class now have only IsValid property.
You can check here:
https://github.com/andrebaltieri/Flunt/blob/dev/Flunt/Notifications/Notifiable.cs

And here is a sample of how can you create your custom notifications:
https://github.com/andrebaltieri/Flunt/blob/dev/Flunt.Tests/CustomNotificationsTests.cs
