### ISSUE TITLE
Validação string IsNotNullOrWhiteSpace

### ISSUE THREAD

**Issue by vteixeira87** [andrebaltieri/Flunt#83]
A validação de string IsNotNullOrWhiteSpace não está funcionando.

Mesmo informando o valor vazio não está add a notificação

**Comment by andrebaltieri** [comment]
Obrigado pelo report! Vou investigar!

**Comment by andrebaltieri** [comment]
@vteixeira87 você estava correto! Corrigi e estou gerando a v2.0.3, em algumas horas estará no ar! Muito obrigado <3
