### ISSUE TITLE
Update Wiki

### ISSUE THREAD

**Issue by AlanNunes** [andrebaltieri/Flunt#86]
The contents in Wiki are out of date. The sample [0.3 Notifications](https://github.com/andrebaltieri/Flunt/wiki/03.-Notifications) is not working in latest versions.

**Comment by ErickMaia** [comment]
I'm stuck with the same problem.

**Comment by andrebaltieri** [comment]
Hi, you just change from:
```csharp
public class MyClass : Notifiable {
```

to
```csharp
public class MyClass : Notifiable<Notification> {
```

Where `Notification` is the base notification class, which contains two properties, `Key` and `Message`.
You can create your custom notification class and use it here also.

Also there`s a sample on the root folder of this repo:
https://github.com/andrebaltieri/Flunt/tree/main/Flunt.Samples

**Comment by ErickMaia** [comment]
Thank you, @andrebaltieri.
