### ISSUE TITLE
Minimizing impact of Contract class changes

### ISSUE THREAD

**Issue by yanjustino** [andrebaltieri/Flunt#90]
### The problem
Current changes in the Contract class have caused crashes in Flunt extendable packages such as Flunt.Br. 

### The solution
In view of the continuity of the operation of these packages, I make the following suggestion:

```csharp
  
    //Add this basic class
    public partial class Contract : Contract<bool> { };


    public partial class Contract<T> : Notifiable<Notification>
    {
        public Contract<T> Requires()
        {
            return this;
        }

        public Contract<T> Join(params Notifiable<Notification>[] items)
        {
            if (items == null) return this;
            foreach (var notifiable in items)
            {
                if (notifiable.IsValid == false)
                    AddNotifications(notifiable.Notifications);
            }

            return this;
        }
    }
```

### justification

Since T is not a state of Contract, there would be no major implications of maintaining a base class.

**Comment by andrebaltieri** [comment]
We already have an implementation of these extensions here:
https://github.com/andrebaltieri/Flunt.Extensions.Br

Does it sounds good?

**Comment by yanjustino** [comment]
Sounds great! 

A question... This Repository is already a nugget package?
