### ISSUE TITLE
Refactor INotifiable

### ISSUE THREAD

**Issue by OliveiraCleidson** [andrebaltieri/Flunt#97]
A classe abstrata Notifiable poderia implementar a interface INotifiable que poderia possuir os métodos e as propriedades que a classe abstrata Notifiable possui hoje.

Por exemplo, quando crio uma interface qualquer que herde INotifiable desejo que ela tenha o AddNotifications (e sua família) e também as propriedade Notifications ou IsValid, ou pelo menos as propriedades.

**Comment by andrebaltieri** [comment]
Muito obrigado pelo feedback @OliveiraCleidson...

Acho que neste caso não mudaria muita coisa, como o Notifiable é uma classe abstrata e o INotifiable é uma interface você poderia "herdar" de ambos:

```csharp
public class MyNotifiable : Notifiable, INotifiable

```

Seria isto que queria?
Se puder, coloca alguns trechos de código pra ajudar a me orientar!

Obrigado pela contribuição 💜
